bolt/PPC64: fix API incompatibilities after rebase to main
Two LLVM API changes occurred during the rebase that broke the PowerPC
BOLT port:

1. MCPlusBuilder::isReversibleBranch() gained a MustPreserveFlags
   parameter. Updated the PowerPC override signature.

2. support::endian::byte_swap() changed from template-parameter
   endianness to runtime-parameter endianness. Updated the PPC64
   .branch_lt patching code in RewriteInstance::patchELFFuncArraysPPC64().

Also removed obsolete test PPC64/ppc64-abs-call-stub.s which tested
the absolute call stub mechanism that was removed in commit 1eb98442fc2b.

Fixes build errors:
  error: 'bool llvm::bolt::PPCMCPlusBuilder::isReversibleBranch(
    const llvm::MCInst&) const' marked 'override', but does not override

  error: no matching function for call to 'byte_swap<uint64_t,
    llvm::endianness::little>(uint64_t&)'